# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the "index.html" file to the web root directory in the container
COPY index.html /usr/share/nginx/html/

# Expose port 80 for incoming HTTP traffic
EXPOSE 80

# Start the Nginx server when the container starts
CMD ["nginx", "-g", "daemon off;"]
