apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: easypay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: my-web-app
          image: hariharan21/my-web-app
          ports:
            - containerPort: 80
          resources:
           limits:
             cpu: 20m
